[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
loglevel=critical

[program:nginx]
command=/usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;"
priority=5
autorestart=true
startsecs=1
startretries=10
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:huawei-proxy]
command=/usr/local/bin/huawei-proxy
priority=5
autorestart=true
startsecs=1
startretries=10
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:alist]
command=/opt/alist/alist server
directory=/opt/alist
priority=10
autorestart=true
startsecs=2
startretries=10
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:sing-box]
command=/usr/local/bin/sing-box run -c /app/config.json
priority=10
autorestart=true
startsecs=2
startretries=10
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:tailscaled]
command=/usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/var/run/tailscale/tailscaled.sock
priority=10
autorestart=true
startsecs=2
startretries=10
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:tailscale-init]
command=/usr/local/bin/tailscale-init.sh
priority=20
autorestart=unexpected
startsecs=0
startretries=10
exitcodes=0
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:alist-init]
command=/usr/local/bin/alist-init.sh
priority=20
autorestart=false
startsecs=0
startretries=0
exitcodes=0
stdout_logfile=/dev/null
stderr_logfile=/dev/null
